from app.schemas.extraction import DocumentType


DOCUMENT_FIELD_CATALOG: dict[DocumentType, list[str]] = {
    DocumentType.COMMERCIAL_INVOICE: [
        "Invoice Number",
        "Invoice Date",
        "Invoice Type",
        "Currency",
        "Incoterm",
        "Payment Terms",
        "PO Number",
        "SO Number",
        "Reference Number",
        "Country of Origin",
        "Country of Export",
        "Country of Import",
        "Shipment Mode",
        "Supplier Name",
        "Supplier Code",
        "Supplier Address",
        "Supplier Country",
        "Supplier Tax ID",
        "Supplier GST/VAT Number",
        "Customer Name",
        "Customer Code",
        "Customer Address",
        "Customer Country",
        "Customer Tax ID",
        "Customer GST/VAT Number",
        "AWB Number",
        "MAWB Number",
        "HAWB Number",
        "BOL Number",
        "Shipment Date",
        "Carrier Name",
        "Forwarder Name",
        "Line Number",
        "Product Code",
        "Product Name",
        "SKU",
        "Part Number",
        "Model Number",
        "Batch Number",
        "Lot Number",
        "Serial Number",
        "Quantity",
        "UOM",
        "Unit Price",
        "Line Value",
        "Manufacturing Date",
        "Expiry Date",
        "Shelf Life",
        "UDI Number",
        "GTIN",
        "Device Classification",
        "Discount",
        "Tax Amount",
        "Freight Charges",
        "Insurance Charges",
        "Invoice Value",
        "Net Value",
        "Gross Value",
    ],
    DocumentType.PACKING_LIST: [
        "Packing List Number",
        "Packing List Date",
        "Invoice Number",
        "PO Number",
        "Shipment Reference",
        "AWB Number",
        "Container Number",
        "Seal Number",
        "Carrier",
        "Forwarder",
        "Package Number",
        "Box Number",
        "Pallet Number",
        "Carton Number",
        "Product Code",
        "Product Name",
        "Batch Number",
        "Lot Number",
        "Serial Number",
        "Quantity",
        "UOM",
        "Gross Weight",
        "Net Weight",
        "Volume",
        "Length",
        "Width",
        "Height",
        "CBM",
        "Manufacturing Date",
        "Expiry Date",
        "Sterile Status",
        "Temperature Requirement",
    ],
    DocumentType.AIR_WAYBILL: [
        "AWB Number",
        "MAWB Number",
        "HAWB Number",
        "Issue Date",
        "Shipment Date",
        "Shipper Name",
        "Shipper Address",
        "Consignee Name",
        "Consignee Address",
        "Notify Party",
        "Carrier Name",
        "Flight Number",
        "Origin Airport",
        "Destination Airport",
        "Transit Airport",
        "Number Of Packages",
        "Gross Weight",
        "Chargeable Weight",
        "Commodity Description",
        "Shipment Value",
        "Tracking Number",
        "Current Status",
        "Expected Delivery Date",
    ],
    DocumentType.BILL_OF_LADING: [
        "BOL Number",
        "Container Number",
        "Seal Number",
        "Vessel Name",
        "Voyage Number",
        "Port Of Loading",
        "Port Of Discharge",
    ],
    DocumentType.BILL_OF_ENTRY: [
        "BOE Number",
        "BOE Date",
        "HS Code",
        "Duty Amount",
        "Customs Value",
        "Importer Name",
        "Exporter Name",
    ],
}


def get_fields_for_document_type(document_type: DocumentType) -> list[str]:
    return DOCUMENT_FIELD_CATALOG[document_type]

